noun1 = input("Noun please: ")
adj1 = input("Adjective please: ")
verb1 = input("Gimme a verb now: ")
noun2 = input("\'Nother noun, please: ")
adj2 = input("Descriptor, quick: ")
noun3 = input("Attribute, thanks: ")
verb2 = input("Doing word: ")
adj3 = input("Another adjective: ")
verb3 = input("Verb, plz: ")
noun4 = input("Name word: ")
verb4 = input("DO it again: ")
adj4 = input("Describe it: ")
verb5 = input("Another acting word please: ")
noun5 = input("Name something: ")
propnoun1 = input("Proper Noun now please, like Neville or New York or Cadbury's: ")
propnoun2 = input("And another: ")
propnoun3 = input("And again: ")
propnoun4 = input("One last proper noun: ")
noun6 = input("Just a few more. Give us another noun: ")
noun7 = input("Noun me again: ")
noun8 = input("Penultimate noun: ")
propnoun5 = input("Penultimate proper noun (like David or Tampax): ")
noun9 = input("Last noun: ")
propnoun6 = input("And for the final word, gimme one more proper noun: ")

print("The Outsong - Kaa\n\nAnger is the " +noun1 +" of Fear--")
print("Only " + adj1 + " eyes see clear. \nCobra-poison none may " + verb1 +"--")
print("Even so with " + noun2 + "-speech.")
print(adj2 + " talk shall call to thee\nStrength, whose mate is " + noun3 + ".")
print("Send no " + verb2 + " beyond thy length.")
print("Lend no " + adj3 + " bough thy strength.")
print(verb3 + " thy gape with buck or goat,")
print("Lest thine " + noun4 + " should choke thy throat.")
print("After gorging, wouldst thou " + verb4 + "?")
print("Look thy den be " +adj4 + " and deep,")
print("Lest a wrong, by thee " + verb5 + ",")
print("Draw thy " + noun5 + " to the spot.")
print(propnoun1 + " and " + propnoun2 + " and " + propnoun3 + " and " + propnoun4 + ",")
print("Wash thy " + noun6 + " and close thy " + noun7 + ".")
print("Pit and rift and blue " + noun8 + ",")
print(propnoun5 + " follow him!")
print("Wood and Water, Wind and " + noun9 + ",")
print(propnoun6 + " go with thee!")